version: "3.8"
services: 
  user-registration-service:
    image: danvi/user-registration-service:1.1
    restart: always
    build: .
    ports:
      - 8080:8080 
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: DanviShanmuki@2
      MYSQL_PORT: 3306
  mysqldb: 
    container_name: mysqldb
    image: mysql
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports: 
     - 3307:3306   
    environment:
      MYSQL_DATABASE: registration
      MYSQL_ROOT_PASSWORD: DanviShanmuki@2